"""Run and save the verified baseline and a discrete research-cost sweep.

Invoke from the project root with ``.venv/bin/python -m src.run_baseline_analysis``.
All reported equilibria are computed during the run; the initial author
prediction is used only as a verification target.
"""

from importlib.metadata import version
import json
from pathlib import Path
import platform

import numpy as np
import pandas as pd

from src.information_acquisition_game import (
    interior_mixed_research_probability,
    payoff_matrices,
    pure_nash_equilibria,
    support_enumeration_results,
)

TOLERANCE = 1e-9
BASELINE_VALUE = 4
BASELINE_COST = 2
COSTS = (0, 1, 2, 3, 4, 5)
OUTPUT_DIR = Path(__file__).resolve().parents[1] / "outputs"


def cost_relation(value, cost):
    if cost == 0:
        return "zero-cost boundary"
    if cost < value:
        return "interior"
    if cost == value:
        return "equal-value boundary"
    return "high-cost"


def analyze_case(value, cost):
    """Cross-check direct pure profiles and any strict-interior mixed profile."""
    a, b = payoff_matrices(value, cost)
    independent_pure = pure_nash_equilibria(value, cost)
    support = support_enumeration_results(value, cost, TOLERANCE)
    nashpy_pure = [
        tuple(item["pure_profile"])
        for item in support["equilibria"]
        if item["classification"] == "pure"
    ]
    pure_agree = set(independent_pure) == set(nashpy_pure)
    if not pure_agree:
        raise AssertionError(
            f"Direct and NashPy pure equilibria disagree for V={value}, c={cost}: "
            f"{independent_pure} versus {nashpy_pure}"
        )

    relation = cost_relation(value, cost)
    analytical_p = None
    nashpy_mixed_p = None
    mixed_agree = None
    if relation == "interior":
        analytical_p = interior_mixed_research_probability(value, cost)
        mixed = [
            item for item in support["equilibria"]
            if item["classification"] == "mixed"
        ]
        if len(mixed) != 1:
            raise AssertionError(
                f"Expected one NashPy interior mixed equilibrium for "
                f"V={value}, c={cost}; got {len(mixed)}"
            )
        candidate = mixed[0]
        nashpy_mixed_p = {
            "agent_a": candidate["agent_a"][0],
            "agent_b": candidate["agent_b"][0],
        }
        target = [analytical_p, 1.0 - analytical_p]
        mixed_agree = bool(
            np.allclose(candidate["agent_a"], target, atol=TOLERANCE, rtol=0.0)
            and np.allclose(candidate["agent_b"], target, atol=TOLERANCE, rtol=0.0)
        )
        if not mixed_agree:
            raise AssertionError(
                f"Analytical and NashPy mixed probabilities disagree for "
                f"V={value}, c={cost}: {target} versus {candidate}"
            )

    return {
        "parameters": {"V": value, "c": cost},
        "relation_to_V": relation,
        "action_order": ["Research", "Skip"],
        "agent_a_payoffs": a.tolist(),
        "agent_b_payoffs": b.tolist(),
        "independent_pure_equilibria": [list(profile) for profile in independent_pure],
        "nashpy_support_enumeration": support["equilibria"],
        "nashpy_warnings": support["warnings"],
        "number_of_pure_equilibria": len(independent_pure),
        "pure_methods_agree": pure_agree,
        "interior_analytical_mixed_applies": relation == "interior",
        "analytical_p_research": analytical_p,
        "nashpy_mixed_p_research": nashpy_mixed_p,
        "analytical_and_nashpy_mixed_agree": mixed_agree,
    }


def _profiles(profiles):
    return ", ".join(f"({a}, {b})" for a, b in profiles)


def _nashpy_description(items):
    return "; ".join(
        f"{item['classification']}: A={item['agent_a']}, B={item['agent_b']}"
        for item in items
    )


def _version_record():
    return {
        "Python": platform.python_version(),
        "numpy": version("numpy"),
        "nashpy": version("nashpy"),
        "pandas": version("pandas"),
        "matplotlib": version("matplotlib"),
    }


def _summary_markdown(baseline, sweep, versions, checks):
    baseline_pure = _profiles(baseline["independent_pure_equilibria"])
    mixed_items = [
        item for item in baseline["nashpy_support_enumeration"]
        if item["classification"] == "mixed"
    ]
    lines = [
        "# Computational Verification Summary",
        "",
        "Generated by `src/run_baseline_analysis.py` from an executed local Python run.",
        "",
        "## Environment",
        "",
        *[f"- {name}: {number}" for name, number in versions.items()],
        "",
        "## Baseline",
        "",
        "- V = 4; c = 2; action order: [Research, Skip].",
        f"- Agent A payoff matrix: `{baseline['agent_a_payoffs']}`.",
        f"- Agent B payoff matrix: `{baseline['agent_b_payoffs']}`.",
        f"- Independent pure-equilibrium result: {baseline_pure}.",
        f"- NashPy support enumeration: {_nashpy_description(baseline['nashpy_support_enumeration'])}.",
        f"- Analytical interior mixed p(Research) = {baseline['analytical_p_research']} for each player.",
        f"- NashPy and analytical mixed probabilities agree within {TOLERANCE}: {baseline['analytical_and_nashpy_mixed_agree']}.",
        f"- Baseline predicted pure-equilibrium check: {'PASS' if checks['predicted_pure_equilibria'] else 'FAIL'}.",
        f"- Baseline payoff-matrix check: {'PASS' if checks['baseline_payoff_matrices'] else 'FAIL'}.",
        "",
        "## Interpretation",
        "",
        "- **Predicted before computation:** The author identified two pure equilibria, (Research, Skip) and (Skip, Research).",
        "- **Computationally verified:** Direct best-response enumeration and NashPy returned those two pure equilibria for V = 4, c = 2; their pure-profile sets agree.",
    ]
    if mixed_items:
        mixed = mixed_items[0]
        lines.append(
            "- **Newly identified during computation:** NashPy also returned a mixed equilibrium "
            f"with A={mixed['agent_a']} and B={mixed['agent_b']}. "
            "The subsequently applied analytical formula p(Research) = 1 − c/V agrees."
        )
    lines.extend([
        "",
        "## Parameter Modification",
        "",
        "Holding V = 4 fixed, the following discrete research costs were checked. "
        "Every listed pure profile was cross-checked between direct best responses and NashPy.",
        "",
        "| c | Case | Independent pure equilibria | NashPy mixed p(Research), if interior | Analytical p(Research), if interior | Mixed check |",
        "| ---: | --- | --- | --- | ---: | --- |",
    ])
    for case in sweep:
        cost = case["parameters"]["c"]
        mixed = case["nashpy_mixed_p_research"]
        nashpy_p = "—" if mixed is None else f"A={mixed['agent_a']}, B={mixed['agent_b']}"
        analytical_p = "—" if case["analytical_p_research"] is None else str(case["analytical_p_research"])
        mixed_check = "N/A" if case["analytical_and_nashpy_mixed_agree"] is None else "PASS"
        lines.append(
            f"| {cost} | {case['relation_to_V']} | "
            f"{_profiles(case['independent_pure_equilibria'])} | "
            f"{nashpy_p} | {analytical_p} | {mixed_check} |"
        )
    lines.extend([
        "",
        "For 0 < c < V, direct best responses yield two asymmetric pure profiles, "
        "and the analytical interior formula gives p(Research) = 1 − c/V; the "
        "tested c = 1, 2, 3 cases agreed with NashPy. At c = 0 and c = V, "
        "the games are degenerate. The direct checker evaluates all four "
        "possible **pure** profiles and lists the equilibria, but finite support-enumeration output "
        "is not a claim to list every equilibrium in any boundary continuum. "
        "At the tested c = 5 > V, only (Skip, Skip) was a pure equilibrium.",
        "",
        "## Evidence Limits",
        "",
        "- These are equilibrium calculations for a formal model, not observations or synthetic agent-behavior results.",
        "- They do not demonstrate that real LLM agents behave this way.",
        "- They do not demonstrate human behavior.",
        "- They do not establish educational effectiveness of a future Hugging Face demo.",
        "",
    ])
    warnings_found = [
        (case["parameters"]["c"], warning)
        for case in sweep for warning in case["nashpy_warnings"]
    ]
    if warnings_found:
        lines.extend(["## NashPy Warnings", ""])
        lines.extend(f"- c = {cost}: {warning}" for cost, warning in warnings_found)
        lines.append("")
    return "\n".join(lines)


def main():
    baseline = analyze_case(BASELINE_VALUE, BASELINE_COST)
    expected_a = np.array([[2.0, 2.0], [4.0, 0.0]])
    expected_b = np.array([[2.0, 4.0], [2.0, 0.0]])
    expected_pure = {("Research", "Skip"), ("Skip", "Research")}
    checks = {
        "baseline_payoff_matrices": bool(
            np.array_equal(baseline["agent_a_payoffs"], expected_a)
            and np.array_equal(baseline["agent_b_payoffs"], expected_b)
        ),
        "predicted_pure_equilibria": bool(
            set(map(tuple, baseline["independent_pure_equilibria"])) == expected_pure
            and {
                tuple(item["pure_profile"])
                for item in baseline["nashpy_support_enumeration"]
                if item["classification"] == "pure"
            } == expected_pure
        ),
    }
    if not all(checks.values()):
        raise AssertionError(f"Baseline verification check failed: {checks}")

    sweep = [analyze_case(BASELINE_VALUE, cost) for cost in COSTS]
    versions = _version_record()
    json_data = {
        "description": "Computed baseline equilibria; not behavioral observations",
        "environment": versions,
        "baseline": baseline,
        "verification_checks": checks,
    }
    rows = []
    for case in sweep:
        mixed = case["nashpy_mixed_p_research"]
        rows.append({
            "V": case["parameters"]["V"],
            "c": case["parameters"]["c"],
            "relation_to_V": case["relation_to_V"],
            "pure_equilibria": _profiles(case["independent_pure_equilibria"]),
            "number_of_pure_equilibria": case["number_of_pure_equilibria"],
            "nashpy_equilibria": json.dumps(case["nashpy_support_enumeration"]),
            "pure_methods_agree": case["pure_methods_agree"],
            "interior_analytical_mixed_applies": case["interior_analytical_mixed_applies"],
            "analytical_p_research": case["analytical_p_research"],
            "nashpy_mixed_p_research_agent_a": None if mixed is None else mixed["agent_a"],
            "nashpy_mixed_p_research_agent_b": None if mixed is None else mixed["agent_b"],
            "analytical_and_nashpy_mixed_agree": case["analytical_and_nashpy_mixed_agree"],
            "nashpy_warnings": json.dumps(case["nashpy_warnings"]),
        })
    summary = _summary_markdown(baseline, sweep, versions, checks)

    OUTPUT_DIR.mkdir(exist_ok=True)
    (OUTPUT_DIR / "baseline_equilibria.json").write_text(
        json.dumps(json_data, indent=2, ensure_ascii=False) + "\n"
    )
    pd.DataFrame(rows).to_csv(OUTPUT_DIR / "cost_sweep.csv", index=False)
    (OUTPUT_DIR / "verification_summary.md").write_text(summary)
    (OUTPUT_DIR / ".gitkeep").unlink(missing_ok=True)

    print("Baseline parameters: V=4, c=2; action order [Research, Skip]")
    print("Agent A payoffs:", baseline["agent_a_payoffs"])
    print("Agent B payoffs:", baseline["agent_b_payoffs"])
    print("Independent pure equilibria:", baseline["independent_pure_equilibria"])
    print("NashPy support enumeration:")
    for item in baseline["nashpy_support_enumeration"]:
        print(" ", item)
    print("Analytical interior p(Research):", baseline["analytical_p_research"])
    print("NashPy mixed p(Research):", baseline["nashpy_mixed_p_research"])
    print("Analytical/NashPy mixed comparison:", "PASS" if baseline["analytical_and_nashpy_mixed_agree"] else "FAIL")
    print("Predicted pure equilibria:", "PASS" if checks["predicted_pure_equilibria"] else "FAIL")
    print("Baseline matrix:", "PASS" if checks["baseline_payoff_matrices"] else "FAIL")
    print("Cost sweep:")
    for case in sweep:
        print(
            f"  c={case['parameters']['c']} ({case['relation_to_V']}): "
            f"pure={case['independent_pure_equilibria']}; "
            f"NashPy={_nashpy_description(case['nashpy_support_enumeration'])}; "
            f"analytical_p={case['analytical_p_research']}; "
            f"mixed_agree={case['analytical_and_nashpy_mixed_agree']}"
        )
    print("Saved:", ", ".join(str(OUTPUT_DIR / name) for name in (
        "baseline_equilibria.json", "cost_sweep.csv", "verification_summary.md"
    )))


if __name__ == "__main__":
    main()
